### ISSUE TITLE
Issue setting up IOHK binary packages on Mac OS X (Catalina)

### ISSUE THREAD

**Issue by omefire** [input-output-hk/plutus-pioneer-program#12]
I'm trying to reduce how long it will take to compile the Plutus playground and have followed the instructions here: https://github.com/input-output-hk/plutus#iohk-binary-cache.

However, I get the following error/message when I try to enter the nix-shell:

![image](https://user-images.githubusercontent.com/4992035/116080868-69f11800-a64e-11eb-9b74-bc19c925f9e3.png)

What can I do to get passed this?

**Comment by nstankov-bg** [comment]
I feel like you might be behind some kind of firewall that's blocking the resolution.

The safest way to do this would be to automatically change your DNS Resolver to something which we know works. ( I don't endorse a specific one ).

You can try

1.1.1.1 (CloudFlare)
1.0.0.1 (CloudFlare)
8.8.8.8 (Google)

Related Article: https://support.apple.com/guide/mac-help/enter-dns-and-search-domain-settings-on-mac-mh14127/mac

**Comment by omefire** [comment]
@nstankov-bg , yeah that was the issue. I fixed it by using a VPN. Thanks!
