### ISSUE TITLE
Merging contributions for documentation

### ISSUE THREAD

**Issue by isedwards** [input-output-hk/plutus-pioneer-program#26]
@brunjlar, @chris-moreton it would be really good to get the [documentation updates that Chris is working on in a fork](https://github.com/chris-moreton/plutus-pioneer-program) periodically merged into the main repository.  Do you both have thoughts on this?

This would give much higher visibility to Chris' efforts.

Also, it raises the question of what licence the original and derived work are made available under (is there a policy on the default licence for code and documentation produced by iohk / cardano foundation?)

cc: @katomm - do you have an idea on licences and will the Plutus Pioneer Program be moving over to the new developer portal?

**Comment by katomm** [comment]
Sorry for the delayed response here. The current approach is to cover things that are available on the mainnet. I assume the portal will be launched well before smart contracts are available on the mainnet. I have already noticed what great work Chris is doing and I would love to see contributions/discuss this with you guys. Ian is it possible to send me an email to tommy.kammerer (at) cardano foundation (dot) org or ping me on Twitter: https://twitter.com/adatainment? Thanks 

cc: @Mercurial FYI

**Comment by luisantonioig** [comment]
Hi @isedwards ,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
