### ISSUE TITLE
Playground client not accessible remotely

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus-pioneer-program#3]
On MacOS there seem to be numerous issues with compiling the English Auction contract. Instead of trying to resolve those, I moved to a Debial10 hosted on GCE. I got the contract compiled and the playground server/client started.

However, because this is a remote machine I cannot access the playground-client on: https://localhost:8009

Instead, I'd like the playground-client to bind to 0.0.0.0, so that I can use the remote IP.

CrossRef: https://github.com/input-output-hk/plutus/issues/2973

**Comment by tdiesler** [comment]
Adding `host: "0.0.0.0"` in `plutus/plutus-playground-client/webpack.config.js` seems to work ...

```
    devServer: {
        contentBase: path.join(__dirname, "dist"),
        compress: true,
        host: "0.0.0.0",
        port: 8009,
        https: true,
        proxy: {
            "/api": {
                target: 'http://localhost:8080'
            }
        }
    },
```

**Comment by tdiesler** [comment]
This is no longer an issue on macOS Big Sur. After updating ghcup, I can run the playground on localhost just fine.

**Comment by thisisraghavkumar** [comment]
@tdiesler where did you update the ghcup, in your local mac or your remote VM? Also did you just create a rule to allow traffic from outside to port 8009 or also to 8080?

**Comment by tdiesler** [comment]
I ran everything locally.
