### ISSUE TITLE
Unable to build EnglishAuction.hs

### ISSUE THREAD

**Issue by Vivek205** [input-output-hk/plutus-pioneer-program#34]
When I run `cabal build` in the folder `code/week01/src/Week01` I'm facing the error below:

![image](https://user-images.githubusercontent.com/26110173/126131183-65d0cae3-94f5-4d75-8e30-27e4e67a55ed.png)
----
The tag in my `cabal.project` file is `ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4`.

I tried checking out `git checkout ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4` but I'm getting error with that as well.
![image](https://user-images.githubusercontent.com/26110173/126131376-29e0c265-d427-4b80-b130-29b8aeda9711.png)

**Comment by Vivek205** [comment]
```
Warning: Requested index-state 2021-06-10T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-06-09T23:01:39Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

**Comment by rc9575** [comment]
try the version fix in `plutus-pioneer-program-week01.cabal` as outlined here: https://github.com/input-output-hk/plutus-pioneer-program/issues/6#issuecomment-824198901 and then run `cabal update`. Then try `cabal build` again

**Comment by Vivek205** [comment]
@rc9575 It worked. Thanks for the support.
