### ISSUE TITLE
Incorrect git commit hash in the week05 cabal.project file

### ISSUE THREAD

**Issue by honungsburk** [input-output-hk/plutus-pioneer-program#35]
the git tag "8f1a47674a99ac9bc2aba3231375d8d6de0641d2" in week 5 appears not to exist in the plutus repo. When running `git pull` and then `git checkout 8f1a47674a99ac9bc2aba3231375d8d6de0641d2` I recieve
`fatal: reference is not a tree: 8f1a47674a99ac9bc2aba3231375d8d6de0641d2`

**Comment by honungsburk** [comment]
Using the hash seen in week 6 seems to work: `8a20664f00d8f396920385947903761a9a897fe0`

**Comment by Tenoke** [comment]
The hash in week1 and on the video for iteration 2 is also incorrect 

```
$ git checkout ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4
fatal: reference is not a tree: ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4
```

**Comment by luisantonioig** [comment]
Hi @honungsburk ,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
