### ISSUE TITLE
Cabal Build creates a Bug Contract?!

### ISSUE THREAD

**Issue by Kaleb47** [input-output-hk/plutus-pioneer-program#42]
Hello, I was just following along the first tutorial in the second cohort. I was able to build the code, but the EnglishAuction.hs has 12 syntax errors. Is that supposed to happen because I thought the homework was just run cabal build and compile and test the code on the plutus-playground. If this is purposeful I'll try to debug it myself but based on what I am reading in the assignment, that's not supposed to happen.

![image](https://user-images.githubusercontent.com/63081938/130370641-f0bffeed-50ea-4449-980d-9edeb5017fef.png)

**Comment by luisantonioig** [comment]
Hi @Kaleb47,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
