### ISSUE TITLE
Incorrect git commit hash in weeks 9 and 10

### ISSUE THREAD

**Issue by lemmon-714** [input-output-hk/plutus-pioneer-program#44]
out of the box, cabal build yields

fatal: reference is not a tree: 09433fe537a4ab57df19e70be309c48d832f6576

Affected Repo: https://github.com/input-output-hk/cardano-ledger-specs
Strangely, week09 has the same issue. 
The value from week08 does not work.

**Comment by mingyunbudui** [comment]
我也遇到了这个错误，不知道该用哪个commit

**Comment by luisantonioig** [comment]
Hi @lemmon-714,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
