### ISSUE TITLE
Proposal - add detailed explanation comments to all the code

### ISSUE THREAD

**Issue by visortelle** [input-output-hk/plutus-pioneer-program#45]
I think it can smooth out the learning curve if you'd add explanation comments on the educational code. 
It's easier to follow the code and understand what happens here.

It may be especially useful for Haskell and/or blockchain newbies as helps to faster establish neural connections between human-readable meaningful text and yet not fully accustomed syntax.

Of course, it's just an opinion and it's debatable.
Thank you.

**Comment by luisantonioig** [comment]
Hi @visortelle,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
