### ISSUE TITLE
Is cabal file right for EnglishAuction compilation?

### ISSUE THREAD

**Issue by logisin** [input-output-hk/plutus-pioneer-program#6]
After trying many times to build the EnglishAuction I finally made it after changing the version of the package from 
^>=14.0.0.1 to ==14.0.0.0.

**Comment by aelqaraoui** [comment]
> After trying many times to build the EnglishAuction I finally made it after changing the version of the package from
> ^>=14.0.0.1 to ==14.0.0.0.

I having the same problem, how did you fix it ??

**Comment by kevinhammond** [comment]
You can edit the relevant cabal.project file.  I have also had this problem, but assumed I had a wrong GHC version

**Comment by kevinhammond** [comment]
Lars confirms you should be using `ghc-8.10.2`

**Comment by kevinhammond** [comment]
I can confirm that this works with `ghc-8.10.2`.  I had to set up a clean Haskell configuration (different user, different machine, exact configuration) to be able to do this, though

**Comment by JonathanLorimer** [comment]
I have tried with `ghc-8.10.4`, `ghc-8.10.2` and `ghc-8.8.4`, I have tried tweaking version bounds and I still always end up with this error:

```
Failed to build cardano-crypto-class-2.0.0. The failure occurred during the
configure step.
Build log (
/home/jonathanl/.cabal/logs/ghc-8.10.2/cardano-crypto-class-2.0.0-d590a1db289d84ac38f0f791b77e4e76982d1a1234f78c4223ce83793b97b919.log
):
Configuring library for cardano-crypto-class-2.0.0..
/nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/ghc: /nix/store/m4x0hqp8amgh987v1862x9hpxpi5rsgj-ncurses-6.2/lib/libtinfo.so.6: no version information available (required by /nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/../haskeline-0.8.0.1/libHShaskeline-0.8.0.1-ghc8.10.2.so)
/nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/ghc: /nix/store/m4x0hqp8amgh987v1862x9hpxpi5rsgj-ncurses-6.2/lib/libtinfo.so.6: no version information available (required by /nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/../ghc-8.10.2/libHSghc-8.10.2-ghc8.10.2.so)
/nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/ghc: /nix/store/m4x0hqp8amgh987v1862x9hpxpi5rsgj-ncurses-6.2/lib/libtinfo.so.6: no version information available (required by /nix/store/4s9k25qaw5ckxml7xczzl5h9r7ym1agh-ghc-8.10.2-binary/lib/ghc-8.10.2/bin/../terminfo-0.4.1.4/libHSterminfo-0.4.1.4-ghc8.10.2.so)
cabal: The program 'pkg-config' version >=0.9.0 is required but it could not
be found.

cabal: Failed to build cardano-crypto-class-2.0.0 (which is required by
plutus-pioneer-program-week01-0.1.0.0). See the build log above for details.
```

**Comment by JonathanLorimer** [comment]
I was trying to put together a `nix-shell` to provide a quick dev environment with the dependencies at the correct version, but I couldn't figure it out. This is incredibly frustrating, and I can't imagine what its like for all the newcomers who have no experience with haskell, cabal, or nix!

**Comment by luisantonioig** [comment]
Hi @logisin,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch. 

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
