### ISSUE TITLE
Error running EnglishAuction

### ISSUE THREAD

**Issue by mzfr** [input-output-hk/plutus-pioneer-program#64]
I have the latest version of plutus playground running. When I tried to run the `EnglishAuction` it gave a lot of errors so I tried to add the changes suggested in #21 but even after that I am getting the following error:

```
Compilation Error, Line 266, Column 27 (jump)
 error:
    Not in scope: ‘Constraints.scriptInstanceLookups’
    Module ‘Ledger.Constraints’ does not export ‘scriptInstanceLookups’.
    |
266 |                 lookups = Constraints.scriptInstanceLookups auctionInstance <>
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation Error, Line 297, Column 31 (jump)
 error:
    Not in scope: ‘Constraints.scriptInstanceLookups’
    Module ‘Ledger.Constraints’ does not export ‘scriptInstanceLookups’.
    |
297 |                     lookups = Constraints.scriptInstanceLookups auctionInstance <>
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

How can I fix this?

**Comment by luisantonioig** [comment]
Hi @mzfr,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
