### ISSUE TITLE
(Week1) - cannot locate plutus-playground-client

### ISSUE THREAD

**Issue by to-curiosity** [input-output-hk/plutus-pioneer-program#66]
1.) I've Clone the The Plutus repository (from main branch)
2.) I can't find plutus-playground-client

**Comment by GuessWhoSamFoo** [comment]
Did you remember to checkout commit `ea0ca4e9f` of the plutus repo as specified in https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week01/cabal.project#L28?

**Comment by to-curiosity** [comment]
Thanks for the response @GuessWhoSamFoo but am i missing something? I can't find that tag in the repo. I am very new at this
![image](https://user-images.githubusercontent.com/67398331/145738857-1e99ce67-eee1-4f09-a012-a43644cb890f.png)

**Comment by GuessWhoSamFoo** [comment]
It's a commit hash, not a tag. From the Plutus repo, `git checkout <hash>`.

See https://stackoverflow.com/questions/50942519/how-to-checkout-a-specific-commit-from-git for a better explanation

**Comment by to-curiosity** [comment]
@GuessWhoSamFoo  thank you so much man, I got it now.
