### ISSUE TITLE
Should recommend `fusion-plugin` for automatic inlining?

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/plutus-pioneer-program#67]
Plutus needs inlining/unfolding of most functions to work.
There is an automatic plugin to do that here:
https://github.com/composewell/fusion-plugin

Should we recommend its use and add `GHC_OPTION` in multimodule examples as a best practice?

See related ticket: https://github.com/input-output-hk/plutus/issues/4277

**Comment by luisantonioig** [comment]
Hi @mgajda,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
