### ISSUE TITLE
Error running nix-shell

### ISSUE THREAD

**Issue by elmerihyvonen** [input-output-hk/plutus-pioneer-program#68]
I have followed the instructions from here: https://docs.plutus-community.com/docs/setup/MacOS.html

I have completed steps 1-9, but when I try to run: 
nix-build -A plutus-playground.client 
or 
nix-build -A plutus-playground.server 
I receive these errors: 
zsh: segmentation fault nix-build -A plutus-playground.client 
zsh: segmentation fault nix-build -A plutus-playground.server

Also when I try to start nix-shell everything froze here:

~ nix-shell 
trace: To materialize project.plan-nix for Agda entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'. 
waiting for lock on '/nix/store/hcjpdhyjhkhz6albg40rqhj7m1dpnmf3-hnix-lib-hnix-0.13.1'...

**Comment by bolshoytoster** [comment]
Could you run `nix-build -vvvA plutus-playground.client` and paste the whole output here in backticks i.e.
\`\`\`
[paste here]
\`\`\`

This could be related to https://github.com/NixOS/nix/issues/3331

**Comment by luisantonioig** [comment]
I think that tutorial is outdated, if you already have nix installed, could you please follow instructions in the second page of [this document](https://docs.google.com/document/d/13112LHG9vVvNUs40oZSqZ-DF6_yFiT_SJZ2NaEmjMM4/edit)?
