### ISSUE TITLE
Absolute numbers

### ISSUE THREAD

**Issue by pkankaras** [input-output-hk/plutus-pioneer-program#7]
How we can get absolute numbers from the slots, is the slot configurable?
@brunjlar

**Comment by brunjlar** [comment]
Just providing some more context: The question is whether there is a way to query the current time from inside the `Contract` monad. You can query the current slot number, of course, and as long as we have a fixed slot duration of one second, it's trivial to convert from slot number to real time. The slot duration could change in the future, however, so the question is how to create long running Plutus contracts (with "deadlines" years in the future) that are resilient against future slot duration changes.

**Comment by kevinhammond** [comment]
Yes, don't assume that slot numbers will give absolute wallclock times.  

They can be converted to blockchain-relative times when the slot duration is known (but that time will not necessarily be exactly the same as the clock time on your local system - the system accepts some "drift").  **Start to think in "blockchain time" and "slots"**

So if the latest blockchain slot is S, the absolute blockchain time will be T=time(S).  If you ask for S+10, that will be T = time(S+10).  At the moment, each slot costs 1s, so T=T+10

What you can't assume is that your wall clock/system clock will also show T+10...

The best analogy would be eg with a stock exchange clock and your personal watch.  If you rely on your watch you may fail to make the deal (or may make it a bit earlier than you intended)

**Comment by luisantonioig** [comment]
Hi @pkankaras,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
