### ISSUE TITLE
isScriptInput is not actually looking only for script inputs

### ISSUE THREAD

**Issue by MartinSchere** [input-output-hk/plutus-pioneer-program#70]
Some contracts in the repository rely on potentially unsafe assumptions. One example is the `isScriptInput` function:

```hs
isScriptInput i = case (txOutDatumHash . txInInfoResolved) i of
    Nothing -> False
    Just _  -> True
```

This assumes that every input that has a datum hash is a script input. However, according to the spec:

> TxOut is the type of transaction outputs. These are extended to include an optional hash
> of a datum. Note that any output can optionally include such a hash, even though only
> phase-2 scripts can actually use the hash value. Since it is in general impossible for the
> ledger implementation to know at the time of transaction creation whether or not an
> output belongs to a phase-2 script, we simply allow any output to contain a hash of a
> datum.

  That could be dangerous, since anyone can fake a script input by just attaching a datum hash.

The solution or the cleaner way is presented in week 6, where they are filtering by validatorHash, which is cleaner for preventing these [double satisfaction](https://plutus.readthedocs.io/en/latest/reference/common-weaknesses/double-satisfaction.html?highlight=double%20satisifcatino) issues

**Comment by Timekiller7** [comment]
@MartinSchere hi!  if this is indeed the case, then the functions in the plutus library, like "isPayToScriptOut", is dangerous too? because of only datum-hash checking

**Comment by luisantonioig** [comment]
Hi @MartinSchere,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
