### ISSUE TITLE
Possible workflow improvement

### ISSUE THREAD

**Issue by andreabedini** [input-output-hk/plutus-pioneer-program#75]
Hi there,

Since `cabal.project` has a source-repository-package entry for plutus app, cabal is going to do a full checkout of the plutus-apps repository during `cabal update`. Therefore it is not strictly needed to have a separate checkout of the plutus-app repo (which we need to sync separately).

In my tests, I am doing the following:

```bash
$ cd code/week01
$ cabal update
$ nix-shell dist-newstyle/src/plutus-ap_-*/shell.nix
[nix-shell:~/.../code/week01]$ cd dist-newstyle/src/plutus-ap_-*/plutus-playground-client && plutus-playground-server
[nix-shell:~/.../code/week01]$ cd dist-newstyle/src/plutus-ap_-*/plutus-playground-client && npm start
```

This has some advantages but also some complications (`dist-newstyle/src/plutus-ap_-*` might look scary to those unfamiliar with cabal and bash). I'll leave it up to you whether you think it's worth changing the instructions.

Thanks for the great content!

**Comment by luisantonioig** [comment]
Hi @andreabedini,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
