### ISSUE TITLE
Explain valuable blockchain actions

### ISSUE THREAD

**Issue by pkankaras** [input-output-hk/plutus-pioneer-program#9]
@brunjlar  reach out Jan to provide more details about valuable blockchain actions.

**Comment by luisantonioig** [comment]
Hi @pkankaras ,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.
